GET http://localhost:7001/api/price_plans
###
POST http://localhost:7001/api/phonebill
Content-Type: application/json
{
    "price_plan": "sms 101",
    "actions": "call, sms"
}
###
POST http://localhost:7001/api/price_plan/create
Content-Type: application/json
{
    "plan_name": "sms 101",
    "call_price": 2.65,
    "sms_price": 0.45
}
###
POST http://localhost:7001/api/price_plan/update
Content-Type: application/json
{
    "id": 5,
    "plan_name": "sms 101",
    "call_price": 2.65,
    "sms_price": 0.45
}
###
POST http://localhost:7001/api/price_plan/delete
Content-Type: application/json
{
    "plan_name": "sms 101"
}
